apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verirag-ingress
  namespace: verirag
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: verirag-fastapi-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verirag-streamlit-service
                port:
                  number: 8501